/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "brand-dark": "#020307",
        "brand-darker": "#0d0d0d",
        "brand-blue": "#00C0FF",
        "brand-blue-dark": "#2E8CAE",
        "brand-blue-hover": "#7dd3fc",
        "brand-green": "#00BC7D",
        "brand-purple": "#8E51FF",
        "brand-orange": "#FF6900",
        "brand-code": "#0B0B0B",
        "accent-purple": "#C478FF",
        "accent-green": "#1AC69C",
        "accent-blue": "#3FA4FF",
        "accent-pink": "#FF32C6",
        "accent-orange": "#FFAC60",
        "accent-purple-deep": "#832E9F",
        "accent-purple-light": "#AF50CB",
        "accent-orange-deep": "#CB3816",
        "accent-orange-light": "#CF6F3B",
        "accent-pink-deep": "#A62368",
        "accent-pink-light": "#E73F98",
        "gray-logo": "#9B9B9B",
        "gray-icon": "#A2A2A2",
        "gray-border": "#EEEEEE",
        "gray-border-dark": "rgba(255, 255, 255, 0.1)",
        "gray-faq": "#3D3D3D",
        "gray-faq-hover": "#696969",
        "glass-white": "rgba(255, 255, 255, 0.05)",
        "glass-border": "rgba(255, 255, 255, 0.1)",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
        serif: ['"Playfair Display"', "serif"],
      },
      spacing: {
        "1.5": "0.375rem",
        "3.5": "0.875rem",
        "4.5": "1.125rem",
        "5.5": "1.375rem",
        "6.5": "1.625rem",
        "7.5": "1.875rem",
        "8.5": "2.125rem",
        "9.5": "2.375rem",
        "10.5": "2.625rem",
      },
    },
  },
  plugins: [],
};
